'use strict';

const presetUI={catalog:null,filter:'全部方案',custom:[],history:[],raw:false,plan:null,planName:'',builderSource:null};
function readLocal(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}}
function customPlans(){return readLocal('dawn-custom-presets-v1',[]).filter(x=>x&&typeof x.name==='string'&&Array.isArray(x.actions));}
function persistCustom(plans){localStorage.setItem('dawn-custom-presets-v1',JSON.stringify(plans));}
function draftKey(){return state.save?'dawn-draft-v2:'+state.save.name+':'+state.save.sha256:null;}
function persistDraft(){const key=draftKey();if(!key)return;if(!state.pending.size){localStorage.removeItem(key);return;}localStorage.setItem(key,JSON.stringify([...state.pending].map(([path,x])=>({path,value:x.value,origin:x.origin||'手动调整'}))));}
function restoreDraft(){if(!state.save||state.pending.size)return;const draft=readLocal(draftKey(),[]);const fields=new Map(state.save.fields.map(f=>[f.path,f]));for(const row of draft.slice(0,1000)){if(fields.has(row.path)&&typeof row.value==='string'&&row.value!==fields.get(row.path).value)state.pending.set(row.path,{field:fields.get(row.path),value:row.value,origin:row.origin||'恢复的草稿'});}if(state.pending.size)toast(`已恢复 ${state.pending.size} 项未导出的修改。`);}
function checkpoint(label){presetUI.history.push({label,entries:[...state.pending].map(([key,x])=>[key,{...x}])});if(presetUI.history.length>20)presetUI.history.shift();}
function afterPendingChange(){persistDraft();renderPending();if(state.page==='saves')renderFields();}
function undoPreset(){const previous=presetUI.history.pop();if(!previous)return;state.pending=new Map(previous.entries);afterPendingChange();toast('已撤销：'+previous.label);}
function queueChanges(changes,label='手动调整',replace=true){
  const usable=changes.filter(x=>x.field&&String(x.value)!==(state.pending.get(x.field.path)?.value??x.field.value));
  if(!usable.length){toast('当前数值已满足目标。');return 0;}
  checkpoint(label);let count=0;
  for(const {field,value} of usable){if(!replace&&state.pending.has(field.path))continue;const text=String(value);if(text===field.value)state.pending.delete(field.path);else state.pending.set(field.path,{field,value:text,origin:label});count++;}
  afterPendingChange();return count;
}
function effective(field){return state.pending.get(field.path)?.value??field.value;}
async function ensurePresetSave(){if(!state.saveName)state.saveName=state.boot.saves.find(s=>!s.error)?.name;if(!state.saveName)throw new Error('先在游戏中保存一次，再刷新工作台。');if(!state.save||state.save.name!==state.saveName){state.save=await api('/api/save?name='+encodeURIComponent(state.saveName));restoreDraft();}return state.save;}
function actionById(id){return presetUI.catalog?.actions.find(x=>x.id===id);}
function planNotice(){const plan=presetUI.plan;if(!plan||plan.save!==state.save?.name)return '';return `<div class="preset-notice"><span>${I('check')}</span><div><strong>${E(presetUI.planName)} · ${plan.count} 项可调整</strong><p>${plan.reports.map(r=>E(r.name+'：'+r.message)).join('；')}</p></div><button class="text-button" data-action="last-preset-preview">查看明细 ${I('arrowRight')}</button></div>`;}
function actionSummary(action){const def=actionById(action.id);if(!def)return action.id;return def.name+(def.parameter?' · '+num(action.value??def.parameter.default)+' '+def.parameter.unit:'');}
function bundleById(id){return presetUI.catalog.bundles.find(x=>x.id===id)||customPlans().find(x=>x.id===id);}
function normalizeCustomActions(actions){
  if(!Array.isArray(actions)||!actions.length||actions.length>presetUI.catalog.actions.length)throw new Error('方案需要包含有效的配置项。');
  const seen=new Set();return actions.map(x=>{const def=actionById(x.id);if(!def||seen.has(x.id))throw new Error('方案包含未知或重复的配置。');seen.add(x.id);if(!def.parameter)return{id:x.id};const value=String(x.value??def.parameter.default);if(!/^\d+$/.test(value)||Number(value)<def.parameter.min||Number(value)>def.parameter.max)throw new Error(def.name+'的目标超出范围。');return{id:x.id,value:Number(value)};});
}
async function renderPresets(){
  $('#main').innerHTML=heading('A LITTLE MAGIC, YOUR WAY','一键方案','选一种玩法，或把常用调整组合成自己的习惯。',`<div class="preset-heading-actions"><button class="button secondary" data-action="import-preset">${I('download')}导入方案</button><button class="button primary" data-action="new-preset">${I('sliders')}自定义方案</button></div>`)+`<div id="preset-content">${loading()}</div>`;
  try{if(!presetUI.catalog)presetUI.catalog=await api('/api/presets');await ensurePresetSave();if(state.page!=='presets')return;renderPresetContent();}catch(error){if($('#preset-content'))$('#preset-content').innerHTML=empty('还不能配置方案',error.message,'file');}
}
function renderPresetContent(){
  const s=state.save;
  $('#preset-content').innerHTML=`<div class="preset-context"><div class="preset-context-main"><span class="save-symbol">${I('file')}</span><div><span class="eyebrow">本次配置的存档</span><select id="preset-save-select" aria-label="预设目标存档">${state.boot.saves.filter(x=>!x.error).map(x=>`<option value="${E(x.name)}" ${x.name===s.name?'selected':''}>${E(x.title)}</option>`).join('')}</select><small>${E(date(s.modified))} · ${s.inventory} 组背包物品</small></div></div><div class="context-stats"><div><span>当前金币</span><strong>${num(s.gold,1)}</strong></div><div><span>可用天赋点</span><strong>${s.talent}<small>点</small></strong></div></div><span class="context-tip">${I('shield')}先加入清单，再决定保存</span></div><div class="preset-intro"><div><span class="eyebrow">CURATED FOR YOUR ADVENTURE</span><h2>省去重复，留住乐趣。</h2><p>目标可以调整，方案可以组合。每一次改变都有清楚的来龙去脉。</p></div><div class="preset-intro-art"><img src="/assets/items/10003.webp" alt="种子"><img src="/assets/items/10201.webp" alt="物品"><span>✦</span></div></div><div class="preset-filter-row"><div class="filter-tabs" aria-label="方案类别">${['全部方案','种植','经营','成长','社交','我的方案'].map(x=>`<button class="filter-tab ${presetUI.filter===x?'active':''}" data-action="preset-filter" data-filter="${x}">${x}</button>`).join('')}</div><span class="results-count">${presetUI.catalog.bundles.length} 套内置方案 · ${presetUI.catalog.actions.length} 项可组合操作</span></div><div id="preset-cards"></div><div class="preset-rules">${presetUI.catalog.rules.map(r=>`<span>${I('check')}${E(r)}</span>`).join('')}</div><section class="single-actions"><div class="section-heading"><h2>只想改一件事？</h2><span class="muted">单项快捷配置</span></div><div class="single-actions-grid">${presetUI.catalog.actions.map(a=>`<button class="single-action" data-action="single-preset" data-rule="${a.id}"><span>${I(a.icon)}</span><strong>${E(a.name)}</strong>${I('chevron')}</button>`).join('')}</div></section>`;
  $('#preset-save-select').addEventListener('change',async e=>{if(state.pending.size){e.target.value=state.saveName;toast('先保存或清空修改清单，再切换存档。');return;}state.saveName=e.target.value;state.save=null;presetUI.history=[];await renderPresets();});
  renderPresetCards();renderPending();
}
function renderPresetCards(){
  const custom=customPlans().map(p=>({...p,custom:true,category:'我的方案',tone:'sage',icon:'sliders',description:p.actions.map(actionSummary).join('；'),subtitle:'按你的习惯组合',art:10005}));
  const all=[...presetUI.catalog.bundles,...custom];const visible=all.filter(p=>presetUI.filter==='全部方案'||p.category===presetUI.filter);
  $('#preset-cards').innerHTML=planNotice()+(visible.length?`<div class="preset-card-grid">${visible.map(p=>`<article class="preset-card tone-${p.tone}"><div class="preset-card-top"><span class="preset-card-symbol">${I(p.icon)}</span><span class="pill ${p.badge?'gold':'subtle'}">${E(p.badge||p.category)}</span>${p.custom?`<button class="icon-button preset-menu" data-action="delete-preset" data-id="${p.id}" title="删除自定义方案" aria-label="删除${E(p.name)}">${I('close')}</button>`:''}</div><h3>${E(p.name)}</h3><p class="preset-subtitle">${E(p.subtitle)}</p><p class="preset-description">${E(p.description)}</p><div class="preset-includes">${p.actions.slice(0,4).map(a=>`<span>${E(actionSummary(a))}</span>`).join('')}${p.actions.length>4?`<span>+${p.actions.length-4} 项</span>`:''}</div><div class="preset-card-actions"><button class="button primary" data-action="apply-preset" data-id="${E(p.id)}">一键加入 ${I('arrowRight')}</button><button class="text-button" data-action="configure-preset" data-id="${E(p.id)}">调整参数</button>${p.custom?`<button class="icon-button" data-action="export-preset" data-id="${p.id}" title="导出方案 JSON" aria-label="导出${E(p.name)}">${I('download')}</button>`:''}</div></article>`).join('')}</div>`:empty('把常用的配置留在这里','创建自己的方案后，就能在不同存档之间重复使用。','bookmark','<button class="button primary" data-action="new-preset">创建我的方案 '+I('arrowRight')+'</button>'));
}
function openPresetBuilder(source=null){
  if(!presetUI.catalog)return;
  const selections=new Map((source?.actions||[]).map(a=>[a.id,a]));presetUI.builderSource=source;
  $('#preset-builder').innerHTML=`<div class="dialog-heading"><div><span class="eyebrow">BUILD YOUR OWN ROUTINE</span><h2>${source?'调整这套方案':'组合你的方案'}</h2></div><button class="icon-button" data-close="preset-builder" aria-label="关闭">${I('close')}</button></div><label class="preset-name-label">方案名称<input id="custom-preset-name" maxlength="40" value="${E(source?.name||'我的日常方案')}" placeholder="给这套方案起个名字"></label><div class="rule-list">${presetUI.catalog.actions.map(a=>{const selected=selections.has(a.id);const value=selections.get(a.id)?.value??a.parameter?.default;return `<section class="rule-card ${selected?'selected':''}"><label class="rule-check"><input type="checkbox" data-rule-id="${a.id}" ${selected?'checked':''}><span class="rule-icon">${I(a.icon)}</span><div><strong>${E(a.name)}</strong><p>${E(a.description)}</p></div></label>${a.parameter?`<div class="rule-parameter" ${selected?'':'hidden'}><label>${E(a.parameter.label)}<span><input type="number" data-rule-value="${a.id}" value="${value}" min="${a.parameter.min}" max="${a.parameter.max}" step="1">${E(a.parameter.unit)}</span></label><div class="amount-chips">${a.parameter.choices.map(c=>`<button type="button" data-action="rule-choice" data-rule="${a.id}" data-value="${c}">${num(c)}${E(a.parameter.unit)}</button>`).join('')}</div>${a.note?`<small>${E(a.note)}</small>`:''}</div>`:''}</section>`;}).join('')}</div><div class="builder-footer"><span id="rule-selected-count"></span><button class="button secondary" data-action="save-custom-preset">${I('bookmark')}${source?.id?.startsWith('custom-')?'保存方案更改':'保存为我的方案'}</button><button class="button primary" data-action="preview-custom-preset">预览配置 ${I('arrowRight')}</button></div>`;
  $('#preset-builder').querySelectorAll('[data-rule-id]').forEach(input=>input.addEventListener('change',()=>{const card=input.closest('.rule-card');card.classList.toggle('selected',input.checked);const parameter=card.querySelector('.rule-parameter');if(parameter)parameter.hidden=!input.checked;updateBuilderCount();}));updateBuilderCount();$('#preset-builder').showModal();
}
function updateBuilderCount(){const count=$('#preset-builder').querySelectorAll('[data-rule-id]:checked').length;$('#rule-selected-count').textContent=`已选择 ${count} 项配置`;}
function builderActions(){return normalizeCustomActions([...$('#preset-builder').querySelectorAll('[data-rule-id]:checked')].map(input=>{const value=$('#preset-builder').querySelector(`[data-rule-value="${input.dataset.ruleId}"]`);return{id:input.dataset.ruleId,...(value?{value:value.value}:{})};}));}
async function requestPreset(actions,name,immediate=false,button=null){
  if(button){button.disabled=true;button.dataset.originalText=button.innerHTML;button.textContent='正在生成…';}
  try{await ensurePresetSave();const normalized=normalizeCustomActions(actions);const result=await api('/api/preset-plan',{save:state.save.name,sha256:state.save.sha256,actions:normalized});if(result.save!==state.save?.name||result.sha256!==state.save.sha256)throw new Error('存档已经切换，请重新生成方案。');presetUI.plan=result;presetUI.planName=name;const conflict=result.edits.some(e=>state.pending.has(e.path)&&state.pending.get(e.path).value!==e.value);if(immediate&&result.count&&!conflict){stagePreset(false);}else showPresetPreview();}
  catch(error){toast(error.message,true);}finally{if(button){button.disabled=false;button.innerHTML=button.dataset.originalText;}}
}
function showPresetPreview(){
  const plan=presetUI.plan;const conflicts=plan.edits.filter(e=>state.pending.has(e.path)&&state.pending.get(e.path).value!==e.value).length;
  $('#preset-preview').innerHTML=`<div class="dialog-heading"><div><span class="eyebrow">YOUR PLAN, MADE CLEAR</span><h2>${E(presetUI.planName)}</h2></div><button class="icon-button" data-close="preset-preview" aria-label="关闭">${I('close')}</button></div><div class="plan-stats"><div><strong>${plan.count}</strong><span>项数值将调整</span></div><div><strong>${plan.reports.filter(x=>x.changed>0).length}</strong><span>项配置适用</span></div><div><strong>${plan.reports.reduce((n,x)=>n+x.unchanged,0)}</strong><span>项已达到目标</span></div></div><div class="plan-reports">${plan.reports.map(r=>`<div><span class="report-icon ${r.changed?'ready':'neutral'}">${I(r.changed?'check':'info')}</span><strong>${E(r.name)}</strong><span>${E(r.message)}</span></div>`).join('')}</div>${plan.count?`<details class="plan-details"><summary>查看 ${plan.count} 项具体变化</summary><div class="change-list">${plan.changes.map(c=>`<div class="change-row"><div><strong>${E(c.label)}</strong><small>${E(c.detail)}</small></div><div class="change-values"><del>${E(c.before)}</del>${I('arrowRight')}<b>${E(c.value)}</b></div></div>`).join('')}</div></details>`:''}${conflicts?`<label class="conflict-option"><input id="overwrite-preset-conflicts" type="checkbox"><span>本次有 ${conflicts} 项与现有清单不同。勾选后采用本次方案；默认保留原有调整。</span></label>`:''}<div class="dialog-actions"><button class="button secondary" data-close="preset-preview">返回</button><button class="button primary" data-action="stage-preset" ${!plan.count?'disabled':''}>加入修改清单 ${I('arrowRight')}</button></div>`;
  $('#preset-preview').showModal();
}
function stagePreset(overwrite){
  if(presetUI.plan.save!==state.save?.name||presetUI.plan.sha256!==state.save.sha256){toast('当前存档已经切换，请重新生成方案。',true);return;}
  const map=new Map(state.save.fields.map(f=>[f.path,f]));const edits=presetUI.plan.edits;const conflicts=edits.filter(e=>state.pending.has(e.path)&&state.pending.get(e.path).value!==e.value);
  const selected=edits.filter(e=>overwrite||!state.pending.has(e.path)||state.pending.get(e.path).value===e.value).map(e=>({field:map.get(e.path),value:e.value}));
  const count=queueChanges(selected,presetUI.planName,true);if($('#preset-preview').open)$('#preset-preview').close();
  if(state.page==='presets')renderPresetCards();
  if(count)toast(`${presetUI.planName}：已加入 ${count} 项${!overwrite&&conflicts.length?`，保留 ${conflicts.length} 项原有调整`:''}。`);
}
function saveCustomPreset(){try{const actions=builderActions();const name=$('#custom-preset-name').value.trim();if(!name)throw new Error('请给方案起个名字。');const plans=customPlans();const existing=plans.findIndex(p=>p.id===presetUI.builderSource?.id);if(existing<0&&plans.length>=30)throw new Error('最多保存 30 套自定义方案。');const entry={id:existing>=0?plans[existing].id:'custom-'+crypto.randomUUID(),name,actions,created:new Date().toISOString()};if(existing>=0)plans[existing]=entry;else plans.push(entry);persistCustom(plans);$('#preset-builder').close();if(state.page==='presets'){presetUI.filter='我的方案';renderPresetContent();}toast('方案已保存，可随时再次使用。');}catch(error){toast(error.message,true);}}
function exportPreset(id){const plan=bundleById(id);if(!plan)return;const blob=new Blob([JSON.stringify({format:'dawn-atelier-preset',version:1,name:plan.name,actions:plan.actions},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=plan.name.replace(/[\\/:*?"<>|]/g,'_')+'.json';anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function importPresetFile(file){if(!file)return;try{if(file.size>65536)throw new Error('方案文件不能超过 64 KB。');const data=JSON.parse(await file.text());if(data.format!=='dawn-atelier-preset'||data.version!==1||typeof data.name!=='string'||!data.name.trim()||data.name.length>40)throw new Error('这不是有效的黎明工坊方案文件。');const actions=normalizeCustomActions(data.actions);openPresetBuilder({name:data.name,actions});toast('已读入方案，可以调整后保存或预览。');}catch(error){toast(error.message,true);}finally{$('#preset-file').value='';}}

function focusedRecords(){
  const all=state.save.fields;const lookup=new Map(all.map(f=>[f.path,f]));const data=[];
  if(state.group==='inventory')for(const field of all){if(!/^BagSaveData\.ItemDataList\[\d+\]\.Count$/.test(field.path))continue;const parent=field.path.slice(0,-6);const id=Number(lookup.get(parent+'.ConfigId')?.value);data.push({field,id,item:state.items.find(x=>x.id===id),name:field.detail,kind:'inventory'});}
  if(state.group==='favor')for(const field of all){if(!/^AllFavorData\.allNPCData\[\d+\]\.favorValue$/.test(field.path))continue;const parent=field.path.slice(0,-11);const id=Number(lookup.get(parent+'.npcID')?.value);data.push({field,id,parent,name:field.detail,kind:'favor'});}
  if(state.group==='tools')for(const field of all){if(!/^AllOprToolSaveData\.OprToolDataList\[\d+\]\.Level$/.test(field.path))continue;const parent=field.path.slice(0,-6);const id=Number(lookup.get(parent+'.ID')?.value);if(id<1||id>4)continue;data.push({field,id,parent,name:field.detail,kind:'tools'});}
  if(state.group==='staff')for(const field of all){if(!/^AllStaffSaveData\.StaffList\[\d+\]\.CurrentSan$/.test(field.path))continue;const parent=field.path.slice(0,-11);const max=Number(lookup.get(parent+'.MaxSan')?.value||0);data.push({field,parent,max,name:lookup.get(parent+'.Name')?.value||'员工',kind:'staff'});}
  return data;
}
function focusedActions(){const map={inventory:[['inventory','补足背包'],['seeds','补足种子'],['materials','补足材料']],favor:[['favor','批量好感'],['gifts','恢复送礼次数']],tools:[['tools','全部升至满级']],staff:[['staff','全员恢复 SAN']],alchemy:[['talent','补足天赋点']]};return (map[state.group]||[]).map(([id,label])=>`<button class="button secondary" data-action="single-preset" data-rule="${id}">${I(actionById(id)?.icon||'star')}${label}</button>`).join('');}
function renderFocusedFields(){
  if(!presetUI.catalog||!['inventory','favor','tools','staff','alchemy'].includes(state.group))return false;
  const controls=`<div class="focused-actions">${focusedActions()}<button class="text-button raw-toggle" data-action="toggle-raw">${presetUI.raw?'返回简洁视图':'查看全部字段'} ${I('code')}</button></div>`;
  if(presetUI.raw)return false;
  if(state.group==='alchemy'){
    const fields=state.save.fields;const talent=fields.find(f=>f.path==='AlchemySaveData.TalentPoint');const level=fields.find(f=>f.path==='AlchemySaveData.Level');const exp=fields.find(f=>f.path==='AlchemySaveData.Exp');
    $('#field-count').textContent='炼金成长';$('#field-results').innerHTML=controls+`<div class="alchemy-dashboard"><div class="alchemy-highlight"><span class="alchemy-symbol">${I('flask')}</span><span class="eyebrow">YOUR NEXT DISCOVERY</span><h3>为灵感留一点余裕</h3><p>准备可用天赋点，在游戏里选择你真正想要的成长方向。</p><strong>${E(talent?effective(talent):'0')}<small>可用天赋点</small></strong><div class="amount-chips">${[10,30,100].map(n=>`<button data-action="talent-target" data-value="${n}">补足到 ${n} 点</button>`).join('')}</div></div><div class="alchemy-stats"><div><span>炼金等级</span><strong>Lv.${E(level?effective(level):'—')}</strong></div><div><span>当前经验</span><strong>${E(exp?effective(exp):'—')}</strong></div><button class="button secondary" data-action="toggle-raw">高级数值调整 ${I('arrowRight')}</button><p>等级、天赋解锁与经验有联动，预设优先准备可自由分配的点数。</p></div></div>`;return true;
  }
  const query=state.fieldQuery.trim().toLowerCase();const records=focusedRecords().filter(r=>!query||`${r.id||''} ${r.name} ${r.field.path}`.toLowerCase().includes(query));const size=9;const pages=Math.max(1,Math.ceil(records.length/size));state.fieldPage=Math.min(state.fieldPage,pages-1);
  $('#field-count').innerHTML=`<b>${records.length}</b> ${state.group==='inventory'?'组物品':state.group==='favor'?'位角色':state.group==='tools'?'类工具':'位员工'}`;
  $('#field-results').innerHTML=controls+(records.length?`<div class="focused-grid ${state.group==='tools'?'tool-grid':''}">${records.slice(state.fieldPage*size,(state.fieldPage+1)*size).map(r=>focusedCard(r)).join('')}</div>${pages>1?`<div class="pagination"><button data-action="field-page" data-delta="-1" ${state.fieldPage===0?'disabled':''}>上一页</button><span>${state.fieldPage+1} / ${pages}</span><button data-action="field-page" data-delta="1" ${state.fieldPage===pages-1?'disabled':''}>下一页</button></div>`:''}`:empty('当前没有匹配的记录','换个关键词，或在游戏保存新的进度后重新读取。'));return true;
}
function focusedCard(r){
  const index=state.save.fields.indexOf(r.field);const value=Number(effective(r.field));const changed=state.pending.has(r.field.path);const edit=`<button class="icon-button" data-action="edit-field" data-index="${index}" aria-label="调整${E(r.name)}">${I('edit')}</button>`;
  if(r.kind==='inventory'){const cap=r.item?.raw?.bnok||0;return `<article class="focused-card ${changed?'has-change':''}"><div class="focused-card-head">${r.field.icon?`<img src="${E(r.field.icon)}" alt="${E(r.name)}">`:`<span class="focused-fallback">${I('bag')}</span>`}<div><h3>${E(r.name)}</h3><span># ${r.id}</span></div>${edit}</div><div class="stock-number"><strong>${num(value)}</strong><span>${cap>1?'堆叠上限 '+num(cap):'独特物品'}</span></div><button class="button secondary" data-action="stock-one" data-index="${index}" data-cap="${cap}" ${cap<=1||value>=Math.min(99,cap)?'disabled':''}>${cap<=1?'独特物品':value>=Math.min(99,cap)?'已备足':'补足到 '+Math.min(99,cap)} ${I('arrowRight')}</button></article>`;}
  if(r.kind==='favor'){const levels=presetUI.catalog.npc_levels[String(r.id)]||[];const current=levels.filter(x=>value>=x.value).at(-1)||{level:0,value:0};const next=levels.find(x=>x.value>value);const end=next?.value||levels.at(-1)?.value||1;return `<article class="focused-card relationship-card ${changed?'has-change':''}"><div class="focused-card-head"><span class="npc-monogram">${E(r.name.slice(0,1))}</span><div><h3>${E(r.name)}</h3><span>好感 Lv.${current.level}</span></div>${edit}</div><div class="relationship-value"><span>${num(value)} 好感</span><small>${next?'下一级 '+num(end):'已达最高配置档位'}</small></div><div class="progress-line"><span style="width:${Math.min(100,Math.max(0,value/end*100))}%"></span></div><button class="button secondary" data-action="favor-one" data-index="${index}" data-value="${end}" ${!next?'disabled':''}>${next?'提升到下一档':'已达目标'} ${I('heart')}</button></article>`;}
  if(r.kind==='tools'){const ranges=presetUI.catalog.tool_ranges[String(r.id)]||[];const range=ranges[Math.min(value-1,ranges.length-1)]||[1,1];return `<article class="focused-card tool-card ${changed?'has-change':''}"><div class="focused-card-head"><span class="focused-fallback">${I(r.id===1?'sprout':r.id===2?'flask':'tool')}</span><div><h3>${E(r.name)}</h3><span>当前范围 ${range.join(' × ')}</span></div><b class="tool-current">Lv.${value}</b></div><div class="tool-levels">${ranges.map((r2,i)=>`<button class="${i+1<=value?'unlocked':''}" data-action="tool-one" data-index="${index}" data-value="${i+1}" ${i+1<=value?'disabled':''}><span>Lv.${i+1}</span><strong>${r2.join('×')}</strong></button>`).join('')}</div><p>点击更高档位即可加入升级清单。</p></article>`;}
  return `<article class="focused-card ${changed?'has-change':''}"><div class="focused-card-head"><span class="npc-monogram">${E(r.name.slice(0,1))}</span><div><h3>${E(r.name)}</h3><span>${r.max>0?'员工精神状态':'特殊员工'}</span></div>${edit}</div><div class="stock-number"><strong>${r.max>0?num(value):'—'}</strong><span>${r.max>0?'/ '+num(r.max)+' SAN':'保留游戏的特殊设定'}</span></div><button class="button secondary" data-action="staff-one" data-index="${index}" data-value="${r.max}" ${r.max<=0||value>=r.max?'disabled':''}>${r.max>0?'恢复到上限':'无需恢复'} ${I('heart')}</button></article>`;
}

async function refreshReviewRuntime(){try{const runtime=await api('/api/runtime');state.boot.runtime=runtime;const button=$('[data-action="apply-save"]');if(button){button.disabled=!runtime.can_apply;button.title=runtime.message;}const note=$('#apply-runtime-note');if(note)note.textContent=runtime.message;}catch{const button=$('[data-action="apply-save"]');if(button)button.disabled=true;}}
async function applyChanges(button){button.disabled=true;button.textContent='正在备份并应用…';try{const result=await api('/api/apply',editBody());state.pending.clear();presetUI.history=[];persistDraft();renderPending();$('#review-content').innerHTML=`<div class="success-content"><div class="success-mark">${I('check')}</div><h3>已应用到 ${E(state.save.title)}</h3><p>原始存档已备份。重新进入游戏，读取这份存档即可生效。</p><a class="button secondary" href="/backups/${E(result.backup)}" download>${I('download')}下载修改前的原档</a><div class="dialog-actions"><button class="button primary" data-action="view-exports">查看操作记录 ${I('arrowRight')}</button></div></div>`;state.save=null;if(state.page==='saves')await loadSave();toast('备份和应用已完成。');}catch(error){toast(error.message,true);button.textContent='备份并直接应用';await refreshReviewRuntime();}}
function renderHistory(data){const list=data.history||[];if(!list.length)return '';return `<section class="operation-history"><div class="section-heading"><h2>最近操作与原档</h2><span class="pill subtle">可回退</span></div><div class="panel">${list.slice(0,12).map(row=>`<div class="export-row">${I(row.mode==='apply'?'check':'archive')}<div><h3>${row.mode==='apply'?'直接应用':'导出修改'} · ${E(row.source)}</h3><p>${E(date(row.created))} · ${row.count} 项调整</p></div><a class="button secondary" href="${E(row.backup_download)}" download>${I('download')}下载原档</a></div>`).join('')}</div></section>`;}

document.addEventListener('click',async event=>{
  const button=event.target.closest('[data-action]');if(!button)return;const action=button.dataset.action;
  if(action==='preset-filter'){presetUI.filter=button.dataset.filter;renderPresetContent();}
  else if(action==='new-preset'){if(!presetUI.catalog)presetUI.catalog=await api('/api/presets');openPresetBuilder();}
  else if(action==='configure-preset')openPresetBuilder(bundleById(button.dataset.id));
  else if(action==='apply-preset'){const p=bundleById(button.dataset.id);await requestPreset(p.actions,p.name,true,button);}
  else if(action==='single-preset'){if(!presetUI.catalog)presetUI.catalog=await api('/api/presets');const def=actionById(button.dataset.rule);openPresetBuilder({name:def.name,actions:[{id:def.id,...(def.parameter?{value:def.parameter.default}:{})}]});}
  else if(action==='rule-choice'){const field=$(`[data-rule-value="${button.dataset.rule}"]`);if(field)field.value=button.dataset.value;}
  else if(action==='preview-custom-preset'){try{const actions=builderActions();const name=$('#custom-preset-name').value.trim()||'自定义方案';$('#preset-builder').close();await requestPreset(actions,name,false,button);}catch(error){toast(error.message,true);}}
  else if(action==='save-custom-preset')saveCustomPreset();
  else if(action==='stage-preset')stagePreset($('#overwrite-preset-conflicts')?.checked||false);
  else if(action==='export-preset')exportPreset(button.dataset.id);
  else if(action==='import-preset'){if(!presetUI.catalog)presetUI.catalog=await api('/api/presets');$('#preset-file').click();}
  else if(action==='delete-preset'){const previous=customPlans();persistCustom(previous.filter(x=>x.id!==button.dataset.id));renderPresetCards();toast('已移除方案；本次修改清单保持原样。');}
  else if(action==='undo-pending')undoPreset();
  else if(action==='last-preset-preview')showPresetPreview();
  else if(action==='refresh-runtime')await refreshReviewRuntime();
  else if(action==='toggle-raw'){presetUI.raw=!presetUI.raw;renderFields();}
  else if(action==='stock-one'){const f=state.save.fields[Number(button.dataset.index)];queueChanges([{field:f,value:Math.max(Number(effective(f)),Math.min(99,Number(button.dataset.cap)))}],'物品补给');}
  else if(action==='favor-one'||action==='staff-one'){const f=state.save.fields[Number(button.dataset.index)];queueChanges([{field:f,value:Math.max(Number(effective(f)),Number(button.dataset.value))}],action==='favor-one'?'好感进阶':'员工恢复');}
  else if(action==='tool-one'){const f=state.save.fields[Number(button.dataset.index)];const selected=state.save.fields.find(x=>x.path===f.path.replace(/\.Level$/,'.SelectedIndex'));queueChanges([{field:f,value:button.dataset.value},{field:selected,value:button.dataset.value}],'工具升级');}
  else if(action==='talent-target')await requestPreset([{id:'talent',value:Number(button.dataset.value)}],'炼金天赋点',true,button);
  else if(action==='apply-save')await applyChanges(button);
});
document.addEventListener('DOMContentLoaded',()=>{$('#preset-file').addEventListener('change',event=>importPresetFile(event.target.files[0]));});
document.addEventListener('keydown',event=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='z'&&!/INPUT|TEXTAREA/.test(document.activeElement.tagName)&&!document.querySelector('dialog[open]')&&presetUI.history.length){event.preventDefault();undoPreset();}});
